import { isConnected } from "@/utils/session";
import { useSession } from "next-auth/react";
import Head from "next/head";
import { useRouter } from "next/router";
import { ReactElement, useEffect } from "react";
import { Header } from "../organisms/Header";

type Props = {
  children: ReactElement<any, any>
}
export default function Layout({ children }: Props) {

    const session = useSession()
    const router = useRouter()

    useEffect(() => {
      if(!isConnected(session)) router.push("/")
    }, [session])

    return (
      <>
        <Head>
        <title>Culture Clash</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
        <main>
            <Header />
            <div className="w-full pr-10 pl-10 mt-5">
            {children}
            </div>
        </main>
      </>
    )
  }